### ISSUE TITLE
2 items selected

### ISSUE THREAD

**Issue by grimes2** [reupen/album_list_panel#136]
On right-click on another item, two items are selected.

![Screenshot 2023-05-06 233230](https://user-images.githubusercontent.com/15456836/236647499-c259062f-39c5-4bb8-9ae6-6637bb29e47f.png)

**Comment by reupen** [comment]
I see the same behaviour as the left panel in File Explorer. It doesn't actually change the selection, it just highlights the item right-clicked on. That's to avoid the playlist etc updating just because you wanted to open the context menu for a different item. Why do you want it to change the selection?

**Comment by grimes2** [comment]
I was confused, because I didn't know to which selected item the context menu belongs. But its a feature, not a bug.
