### ISSUE TITLE
Initialisation 0s

### ISSUE THREAD

**Issue by grimes2** [reupen/album_list_panel#139]
Populate on initialisation is activated. Console shows always 0s, but the population lasts in total about 2s.

Console:
>[23:10:13] Album list panel: initialised in 0.000 s
>[23:10:13] Album list panel: initialised in 0.000 s
>[23:10:13] Album list panel: initialised in 0.000 s
>[23:10:13] Album list panel: initialised in 0.000 s
>[23:10:13] Album list panel: initialised in 0.000 s
>[23:10:13] Album list panel: initialised in 0.000 s
>[23:10:13] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s
>[23:10:14] Album list panel: initialised in 0.000 s

**Comment by reupen** [comment]
Because the media library initialises in the background in foobar2000 2.0, it usually initialises after the UI first loads (and even when it does initialise, it's often in chunks). So 0s is reported simply because the media library was empty when the panel initialised.

Getting an accurate measurement is a bit more complex, although it should be possible.
