### ISSUE TITLE
Auto-hide panel in horizontal splitter get stuck open when Album List Panel is used

### ISSUE THREAD

**Issue by kborowinski** [reupen/album_list_panel#2]
Album List Panel with "auto send to playlist" option selected causes auto-hide horizontal splitter to get stuck open when changing nodes in album list panel

Album List Panel : 0.3.7 (the same problem observed with previous version)
Columns UI: 0.4.0 (the same problem observed with previous version)
Foobar2000: 1.3.10

**Comment by reupen** [comment]
I haven't been able to reproduce this using just Columns UI and Album list panel on Windows 10 and on Windows 7.

Could you describe the exact sequence of steps that result it in getting stuck open? E.g. hover over splitter divider to make it show, click on Album list panel node, click on another node, move the pointer outside the splitter.

Could you export your layout and attach the FCL file? (You'll need to zip it first.)

What playlist view are you using? What version of Windows?

**Comment by kborowinski** [comment]
Playlist view: NG Playlist
Windows 10.0.10586.218 x64

The FCL and very short mp4 video reproducing the problem is included int data.zip file. I hope the video is self explanatory.


[data.zip](https://github.com/reupen/album_list_panel/files/245034/data.zip)

**Comment by reupen** [comment]
Thanks, I managed to reproduce it.

The problem is related to the amount of time it takes to update the playlist view (which seems a bit slow in your case due to grouping and the number of tracks).

The bug is in Columns UI, and I'll fix it there when I get a chance. 

In the meantime, as a workaround, you can set/create a DWORD under `HKEY_CURRENT_USER\Control Panel\Desktop` named `LowLevelHooksTimeout` and with a value of something like 5000 in decimal (it's in milliseconds, it needs to be longer than the amount of time it takes the playlist view to update when selecting a node in Album list panel). You'll have to log out and in for it to take effect.

**Comment by kborowinski** [comment]
Thanks, the registry workaround works perfectly.

**Comment by reupen** [comment]
No problem :+1:

**Comment by reupen** [comment]
Moved to https://github.com/reupen/columns_ui/issues/35.
