### ISSUE TITLE
Colour System instead of Global

### ISSUE THREAD

**Issue by grimes2** [reupen/album_list_panel#3]
In References | Display | Columns UI | Colours and fonts | Colours  Album list panel is in mode Global. But the colour of the background of the selected item indicates mode System and not Global.

**Comment by reupen** [comment]
Basically, as it is right now the panel does not allow custom selection colours. So, those colours always show there as the system colours (which is also wrong in themed mode...)

As it turns out, it isn't too hard to add the ability to customise the selection colours, which I assume is what you wanted?

**Comment by grimes2** [comment]
I don't understand. In the panel, themed mode shows themed colours, system mode shows system colours, but global mode shows a mixture between system and global colours  (Selected item + Inactive selected item: system colours; Item: global colours. I want, that the panel shows in global mode only global colours. The panels Item properties or Playlist switcher show these global colours.

**Comment by grimes2** [comment]
Thanks.

**Comment by reupen** [comment]
Thanks – that should be fixed by https://github.com/reupen/album_list_panel/pull/6.
